### ISSUE TITLE
How to know when digitalWrite is done?

### ISSUE THREAD

**Issue by lorenwest** [hybridgroup/cylon-beaglebone#29]
Hello,

My robot has many IO pins with operations happening on different pins.  I am writing a driver that sends bits serially down a pin, and need to know when a particular digitalWrite is complete so I can send the next bit down that pin.

It appears that I can listen for the digitalWrite event on the entire board, but with many things happening at once, I need to know when the digitalWrite is complete for the pin that I sent it to.  The digitalWrite event doesn't contain the pin information, just that a write occurred on the board and the value of the write.

How can I know when a specific digitalWrite is complete?

Thank you,
-Loren

**Comment by edgarsilva** [comment]
Hi @lorenwest,

Are you using any of the cylon-gpio drivers? like directPin? or just completely writing your own?

Anyways eitherway the adaptor is not sending it back in the event args at the momment, but sounds like a good thing to have, I will add it and update, I will provide a branch for you to give it a try afterwards.

Regards,

**Comment by edgarsilva** [comment]
You can give this branch a try:

https://github.com/hybridgroup/cylon-beaglebone/tree/add-pinnum-to-events

Now in the driver you should be able to do something like:

```javascript
DirectPin.prototype.digitalWrite = function(value) {
  this.connection.on('digitalWrite', function(value, pinNum) {
    console.log('PinNum: ', pinNum);
    console.log('Value:', value);
  });
  this.connection.digitalWrite(this.pin, value);
};
```

This will merged to master and published to npm in shortly, but that branch should work for you.

Let me know how it goes.

**Comment by edgarsilva** [comment]
On a side note, it seems you should be able to imitate that behavior with the direct-pin driver, and that driver instance should have the pinNum and you can listen directly for the write to be done in the whatever pin you need.

**Comment by lorenwest** [comment]
Hi @edgarsilva, I'm writing a driver for a specific chip, and am calling digitalWrite on the connection given to the driver.  Currently I'm testing on a beaglebone, but I'd like the driver to be useful regardless of the connection it's given.

Is it possible to write a driver that uses another driver as the implementation?  I see the direct-pin event emitter emits on a pin object, so I'd be able to listen on a pin by pin basis.

Thanks,
-Loren

**Comment by lorenwest** [comment]
..and thank you for adding the pin number to the event!

**Comment by edgarsilva** [comment]
You should be able to do it, but you would need to setup and pass all appropiate attributes to the driver itself when instantiating, in this case it would be easier to use the direct connection, what would happen is that we would need to update our adaptors that use GPIO to pass the pinNum back in when they emit the event.

I'll do that later, since I think is a worth it to send that info back, but for the time being only beaglebone will work on that branch.

I'll update the other adaptors so we can probably cut a release with these changes next week.

Once I do that your driver should work pretty much on every platform that can use GPIO.

**Comment by lorenwest** [comment]
Thanks - for the short term I'll use the direct-pin driver so I can deploy without a custom cylon-beaglebone build.  When this is all in place I'll go back to using the connection directly.

While you're in that code, adding a callback arg would be nice... :)

**Comment by edgarsilva** [comment]
Sure, I'll take a look into it and see if I can add callbacks for all the reads and writes.

**Comment by edgarsilva** [comment]
This was addressed a while back, pls reopen or create a new issue if you notice any problem.
